import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Stat from "./components/stat";

const myFont = localFont({
  src: "./lazlo.woff2",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <div className="drawer lg:drawer-open">
          <input id="my-drawer-2" type="checkbox" className="drawer-toggle" />
          <div className="drawer-content flex flex-col items-start justify-start">
            {/* Page content here */}
            <label htmlFor="my-drawer-2" className="drawer-button lg:hidden">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="32"
                height="32"
                viewBox="0 0 32 32"
                id="setting"
                className="hover:rotate-180 transition-transform cursor-pointer"
              >
                <path d="M27.526 12.682a11.906 11.906 0 0 0-1.028-2.492l1.988-4.182a16.159 16.159 0 0 0-2.494-2.494L21.81 5.502a11.97 11.97 0 0 0-2.492-1.028L17.762.102C17.184.038 16.596 0 16 0s-1.184.038-1.762.102l-1.556 4.372c-.874.252-1.71.596-2.49 1.028L6.008 3.514a16.159 16.159 0 0 0-2.494 2.494l1.988 4.182a11.97 11.97 0 0 0-1.028 2.492L.102 14.238C.038 14.816 0 15.404 0 16s.038 1.184.102 1.762l4.374 1.556c.252.876.594 1.71 1.028 2.492l-1.988 4.182c.738.92 1.574 1.758 2.494 2.494l4.182-1.988c.78.432 1.616.776 2.492 1.028L14.24 31.9c.576.062 1.164.1 1.76.1s1.184-.038 1.762-.102l1.556-4.374c.876-.252 1.71-.594 2.492-1.028l4.182 1.988a16.071 16.071 0 0 0 2.494-2.494l-1.988-4.182a11.97 11.97 0 0 0 1.028-2.492L31.9 17.76c.062-.576.1-1.164.1-1.76s-.038-1.184-.102-1.762l-4.372-1.556zM16 24a8 8 0 1 1 0-16 8 8 0 0 1 0 16zm-4-8a4 4 1080 1 0 8 0 4 4 1080 1 0-8 0z"></path>
              </svg>
            </label>
          </div>
          <div className="drawer-side items-center">
            <label
              htmlFor="my-drawer-2"
              aria-label="close sidebar"
              className="drawer-overlay"
            ></label>
            <ul className="menu bg-two-color rounded-tr-xl rounded-br-xl p-4 w-72 min-h-screen text-base-content">
              <div className="relative h-93 lg:h-[100%] overflow-y-auto">
                <li>
                  <a>Sidebar Item 1</a>
                </li>
                <li>
                  <a>Sidebar Item 2</a>
                </li>
                <li>
                  <a>Sidebar Item 2</a>
                </li>
                <li>
                  <a>Sidebar Item 2</a>
                </li>
                <li>
                  <a>Sidebar Item 2</a>
                </li>
                <li>
                  <a>Sidebar Item 2</a>
                </li>
                <li>
                  <a>Sidebar Item 2</a>
                </li>
                <li>
                  <a>Sidebar Item 2</a>
                </li>
                <li>
                  <a>Sidebar Item 2</a>
                </li>
                <li>
                  <a>Sidebar Item 2</a>
                </li>
                <li>
                  <a>Sidebar Item 2</a>
                </li>
                <li>
                  <a>Sidebar Item 2</a>
                </li>
                <li>
                  <a>Sidebar Item 2</a>
                </li>
                <li>
                  <a>Sidebar Item 2</a>
                </li>
                <li>
                  <a>Sidebar Item 2</a>
                </li>
                <li>
                  <a>Sidebar Item 2</a>
                </li>
              </div>
              {/* <div className="absolute w-full h-24 bottom-0 right-0 left-0 mr-auto ml-auto border-t border-t-black"> */}

              <li className="fixed px-3 bottom-0 left-0 right-0 ml-auto mr-auto border-t border-t-black">
                <Stat/>
              </li>
            </ul>
          </div>
        </div>
        {children}
        <script></script>
      </body>
    </html>
  );
}
